version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - arnavs-0
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.30
    - 1.4.32
  - dependency-name: com.airbnb.android:lottie
    versions:
    - 3.6.1
  - dependency-name: com.clarifai:clarifai-grpc
    versions:
    - 7.0.1
    - 7.1.0
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
  - dependency-name: com.google.firebase:firebase-database
    versions:
    - 19.6.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
